# Docker Compose configuration for Dev API Vault

version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - FASTAPI_ENV=development
      - DEBUG=true
      - RAPIDAPI_PROXY_SECRET=${RAPIDAPI_PROXY_SECRET:-development_secret}
    volumes:
      # Mount source code for development (remove in production)
      - ./app:/app/app
      - ./tests:/app/tests
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: unless-stopped

  # Optional: Add a reverse proxy for production
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    profiles:
      - production